# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QA Simple Rewards' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for QA Simple Rewards
pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON'
pod 'SwiftSpinner'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
pod 'AlamofireImage', '~> 3.1'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Kingfisher', '~> 3.0'
end
